---
- name: Testing andrewrothstein.tls (nothing specified with no ill consequence)
  hosts: all
  roles:
    - '{{ playbook_dir }}'
- name: Testing andrewrothstein.tls
  hosts: all
  tasks:
    # now test for real
    - name: Mkdir pki directories
      with_items:
        - pki-1
        - pki-2
        - pki-3
      ansible.builtin.file:
        path: /tmp/{{ item }}
        state: directory
        mode: '755'
    - name: Only a CA
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
      vars:
        tls_src: '{{ playbook_dir }}/test-pki'
        tls_dest: /tmp/pki-1
        tls_kinds:
          - ca
    - name: Full client/server
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
      vars:
        tls_src: '{{ playbook_dir }}/test-pki'
        tls_dest: /tmp/pki-2
    - name: Full client/server with destination file names not default
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
      vars:
        tls_src: '{{ playbook_dir }}/test-pki'
        tls_dest: /tmp/pki-3
        tls_dest_file_names:
          ca: ca.pem
          cert: client-cert.pem
          key: client-key.pem
