---
- name: Installing certs and keys
  when: tls_src is defined and tls_dest is defined
  block:
    - name: Installing certs and keys by kind
      loop: '{{ tls_kinds }}'
      loop_control:
        loop_var: tls_kind
      ansible.builtin.include_tasks: 'install-{{ tls_installer }}.yml'
